run:
    timeout: 5m
    go: "1.21"
    modules-download-mode: readonly

linters:
    disable-all: true
    enable:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - typecheck
        - unused
        - revive
        - gosec

issues:
    exclude-use-default: false
    max-issues-per-linter: 0
    max-same-issues: 0
